### ISSUE TITLE
Question: What's the theme you use in README?

### ISSUE THREAD

**Issue by Yukaii** [cdonohue/vscode-quill-icons#1]
Really nice icon theme 😍 Just want to know what's the theme in README screenshots.

**Comment by cdonohue** [comment]
Thanks for the kind words, @Yukaii. I'll update the README with the theme information.

**Comment by cdonohue** [comment]
@Yukaii check out https://github.com/cdonohue/vscode-quill-icons/blob/master/README.md#themes-shown

**Comment by Yukaii** [comment]
Thank you @cdonohue !
