### ISSUE TITLE
png files not showing an icon

### ISSUE THREAD

**Issue by sfrench87** [cdonohue/vscode-quill-icons#2]
Using the light theme png's don't show an icon.

**Comment by cdonohue** [comment]
Thanks for mentioning this @sfrench87 . I’ll get a PR ready soon.

**Comment by sfrench87** [comment]
![Capture](https://user-images.githubusercontent.com/48254143/69618329-a1126280-1031-11ea-8cbb-dabeb81c0b2f.JPG)

Thanks, beautiful set of icons, just noticed jpgs don't show the image icon.

**Comment by cdonohue** [comment]
I have an update going out now for this @sfrench87 . Please give it another try and let me know if that works.

**Comment by sfrench87** [comment]
All works perfectly now, thank you for the quick fix.
