### ISSUE TITLE
Color Theme

### ISSUE THREAD

**Issue by rutkowskic** [cdonohue/vscode-quill-icons#5]
Hey Where can i find the color theme that is in the first picture which is in the section Overview - https://marketplace.visualstudio.com/items?itemName=cdonohue.quill-icons&ssr=false#overview

**Comment by jacobwgillespie** [comment]
Hey, I believe if you scroll down a bit, the color themes are described on that same page: https://marketplace.visualstudio.com/items?itemName=cdonohue.quill-icons&ssr=false#user-content-themes-shown
